version: 2
jobs:
  build:
    docker:
      - image: "crystallang/crystal:0.27.0"
    environment:
      DOCS_PATH: "docs"
      GIT_USER: "icyleaf"
      GIT_EMAIL: "icyleaf.cn@gmail.com"
      GIT_REPO: "git@github.com:icyleaf/swagger.git"
      GH_REF: "https://github.com/icyleaf/swagger"
      GH_URL: "https://icyleaf.github.io/swagger"
    working_directory: ~/halite
    steps:
      - checkout
      - run:
          name: "Crystal Version"
          command: crystal version
      - run:
          name: "Format"
          command: crystal tool format --check
      - run:
          name: "Specs"
          command: crystal spec
      - run:
          name: "Generate API documents"
          command: crystal docs
      - deploy:
          name: "Upload to gh-page"
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ] && [ ! "${CIRCLE_PR_NUMBER}" ]; then
              git config --global user.name "$GIT_USER"
              git config --global user.email "$GIT_EMAIL"
              cd "${DOCS_PATH}"
              git init
              git remote add origin $GIT_REPO
              git fetch origin
              if ! [ -z `git branch -r | grep gh-pages` ]; then git reset origin/gh-pages; fi
              git add -A .
              git commit --allow-empty -m "Updating documents"
              git push origin HEAD:gh-pages
            fi
